version: '3'

services:
#  postgres:
#    container_name: postgres
#    restart: always
#    image: postgres:10
#    env_file: .env
#    volumes:
#      - dbdata:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
  app:
    container_name: app
    restart: always
    build: .
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8080:8080"


volumes:
  dbdata: